### ISSUE TITLE
Host these notes (and IRC meeting logs) somewhere permanent

### ISSUE THREAD

**Issue by jnewbery** [ajtowns/taproot-review#47]
These review notes, and the meeting logs from the Q&A sessions are a very useful resource and historical record. Perhaps they should be hosted on a dedicated website somewhere?

**Comment by harding** [comment]
What's wrong with here?

**Comment by jnewbery** [comment]
> What's wrong with here?

Nothing, but I think having a website with a dedicated URL has a few advantages:

- we're not relying on github, and can move hosting without breaking links
- this repo doesn't contain the meeting logs, which I think are also useful/interesting
- aesthetically, a website could be a bit nicer than a github repo.

**Comment by ajtowns** [comment]
#48 opened to add meetbot logs; that doesn't include the full channel logs though.
#49 opened to remove a couple of hardcoded github links, so can move hosting more trivially.
